CREATE DATABASE milestone3;

CREATE TABLE IF NOT EXISTS public.table_m3
(
    "SK_ID_CURR" integer,
    "TARGET" integer,
    "NAME_CONTRACT_TYPE" text COLLATE pg_catalog."default",
    "CODE_GENDER" text COLLATE pg_catalog."default",
    "FLAG_OWN_CAR" text COLLATE pg_catalog."default",
    "FLAG_OWN_REALTY" text COLLATE pg_catalog."default",
    "CNT_CHILDREN" integer,
    "AMT_INCOME_TOTAL" float,
    "AMT_CREDIT" float,
    "AMT_ANNUITY" float,
    "AMT_GOODS_PRICE" float,
    "NAME_TYPE_SUITE" text COLLATE pg_catalog."default",
    "NAME_INCOME_TYPE" text COLLATE pg_catalog."default",
    "NAME_EDUCATION_TYPE" text COLLATE pg_catalog."default",
    "NAME_FAMILY_STATUS" text COLLATE pg_catalog."default",
    "NAME_HOUSING_TYPE" text COLLATE pg_catalog."default",
    "REGION_POPULATION_RELATIVE" float,
    "DAYS_BIRTH" integer,
    "DAYS_EMPLOYED" integer,
    "DAYS_REGISTRATION" float,
    "DAYS_ID_PUBLISH" integer,
    "OWN_CAR_AGE" float,
    "FLAG_MOBIL" integer,
    "FLAG_EMP_PHONE" integer,
    "FLAG_WORK_PHONE" integer,
    "FLAG_CONT_MOBILE" integer,
    "FLAG_PHONE" integer,
    "FLAG_EMAIL" integer,
    "OCCUPATION_TYPE" text COLLATE pg_catalog."default",
    "CNT_FAM_MEMBERS" float,
    "REGION_RATING_CLIENT" integer,
    "REGION_RATING_CLIENT_W_CITY" integer,
    "WEEKDAY_APPR_PROCESS_START" text COLLATE pg_catalog."default",
    "HOUR_APPR_PROCESS_START" integer,
    "REG_REGION_NOT_LIVE_REGION" integer,
    "REG_REGION_NOT_WORK_REGION" integer,
    "LIVE_REGION_NOT_WORK_REGION" integer,
    "REG_CITY_NOT_LIVE_CITY" integer,
    "REG_CITY_NOT_WORK_CITY" integer,
    "LIVE_CITY_NOT_WORK_CITY" integer,
    "ORGANIZATION_TYPE" text COLLATE pg_catalog."default",
    "EXT_SOURCE_1" float,
    "EXT_SOURCE_2" float,
    "EXT_SOURCE_3" float,
    "APARTMENTS_AVG" float,
    "BASEMENTAREA_AVG" float,
    "YEARS_BEGINEXPLUATATION_AVG" float,
    "YEARS_BUILD_AVG" float,
    "COMMONAREA_AVG" float,
    "ELEVATORS_AVG" float,
    "ENTRANCES_AVG" float,
    "FLOORSMAX_AVG" float,
    "FLOORSMIN_AVG" float,
    "LANDAREA_AVG" float,
    "LIVINGAPARTMENTS_AVG" float,
    "LIVINGAREA_AVG" float,
    "NONLIVINGAPARTMENTS_AVG" float,
    "NONLIVINGAREA_AVG" float,
    "APARTMENTS_MODE" float,
    "BASEMENTAREA_MODE" float,
    "YEARS_BEGINEXPLUATATION_MODE" float,
    "YEARS_BUILD_MODE" float,
    "COMMONAREA_MODE" float,
    "ELEVATORS_MODE" float,
    "ENTRANCES_MODE" float,
    "FLOORSMAX_MODE" float,
    "FLOORSMIN_MODE" float,
    "LANDAREA_MODE" float,
    "LIVINGAPARTMENTS_MODE" float,
    "LIVINGAREA_MODE" float,
    "NONLIVINGAPARTMENTS_MODE" float,
    "NONLIVINGAREA_MODE" float,
    "APARTMENTS_MEDI" float,
    "BASEMENTAREA_MEDI" float,
    "YEARS_BEGINEXPLUATATION_MEDI" float,
    "YEARS_BUILD_MEDI" float,
    "COMMONAREA_MEDI" float,
    "ELEVATORS_MEDI" float,
    "ENTRANCES_MEDI" float,
    "FLOORSMAX_MEDI" float,
    "FLOORSMIN_MEDI" float,
    "LANDAREA_MEDI" float,
    "LIVINGAPARTMENTS_MEDI" float,
    "LIVINGAREA_MEDI" float,
    "NONLIVINGAPARTMENTS_MEDI" float,
    "NONLIVINGAREA_MEDI" float,
    "FONDKAPREMONT_MODE" text COLLATE pg_catalog."default",
    "HOUSETYPE_MODE" text COLLATE pg_catalog."default",
    "TOTALAREA_MODE" text COLLATE pg_catalog."default",
    "WALLSMATERIAL_MODE" text COLLATE pg_catalog."default",
    "EMERGENCYSTATE_MODE" text COLLATE pg_catalog."default",
    "OBS_30_CNT_SOCIAL_CIRCLE" float,
    "DEF_30_CNT_SOCIAL_CIRCLE" float,
    "OBS_60_CNT_SOCIAL_CIRCLE" float,
    "DEF_60_CNT_SOCIAL_CIRCLE" float,
    "DAYS_LAST_PHONE_CHANGE" float,
    "FLAG_DOCUMENT_2" integer,
    "FLAG_DOCUMENT_3" integer,
    "FLAG_DOCUMENT_4" integer,
    "FLAG_DOCUMENT_5" integer,
    "FLAG_DOCUMENT_6" integer,
    "FLAG_DOCUMENT_7" integer,
    "FLAG_DOCUMENT_8" integer,
    "FLAG_DOCUMENT_9" integer,
    "FLAG_DOCUMENT_10" integer,
    "FLAG_DOCUMENT_11" integer,
    "FLAG_DOCUMENT_12" integer,
    "FLAG_DOCUMENT_13" integer,
    "FLAG_DOCUMENT_14" integer,
    "FLAG_DOCUMENT_15" integer,
    "FLAG_DOCUMENT_16" integer,
    "FLAG_DOCUMENT_17" integer,
    "FLAG_DOCUMENT_18" integer,
    "FLAG_DOCUMENT_19" integer,
    "FLAG_DOCUMENT_20" integer,
    "FLAG_DOCUMENT_21" integer,
    "AMT_REQ_CREDIT_BUREAU_HOUR" float,
    "AMT_REQ_CREDIT_BUREAU_DAY" float,
    "AMT_REQ_CREDIT_BUREAU_WEEK" float,
    "AMT_REQ_CREDIT_BUREAU_MON" float,
    "AMT_REQ_CREDIT_BUREAU_QRT" float,
    "AMT_REQ_CREDIT_BUREAU_YEAR" float
);

COPY table_m3
FROM 'C:\Users\Public\P2M3_fauzan_risqullah_data_raw.csv'
DELIMITER ','
CSV HEADER;

